title: KikoPlay
description: KikoPlay's Blog
author: Kikyou
logo: /static/img/avatar.png
github: https://github.com/Protostars/KikoPlay/
about: KikoPlay

#baseurl: "https://codeasashu.github.io/hcz-jekyll-blog"
#url: "https://codeasashu.github.io/hcz-jekyll-blog"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
exclude:
  - .vs/
  - KikoPlay.pro.user
  - .qmake.stash
  - GeneratedFiles/
  - KikoPlay.VC.VC.opendb
  - KikoPlay.VC.db
  - KikoPlay.sln
  - KikoPlay.vcxproj
  - KikoPlay.vcxproj.filters
  - KikoPlay.vcxproj.user
  - Win32/
  - kikoplay.aps
  - release/
  - debug/
  - x64
